---
version: '3.1'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  redis:
    image: redis:latest
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  webserver:
    image: finx-airflow:latest
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - WAIT_FOR=postgres:5432
    depends_on:
      - postgres
    volumes:
      - ./dags:/root/airflow/dags
      - ./logs:/root/airflow/logs
    ports:
      - "8080:8080"
    command: upgradedb_webserver

  scheduler:
    image: finx-airflow:latest
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - WAIT_FOR=webserver:8080
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    depends_on:
      - webserver
    volumes:
      - ./dags:/root/airflow/dags
      - ./logs:/root/airflow/logs
    command: scheduler

  cli:
    image: finx-airflow:latest
    profiles:
      - debug
    environment:
      CONNECTION_CHECK_MAX_COUNT: "0"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
    command:
      - bash
      - -c
      - airflow
    depends_on:
      - postgres
    volumes:
      - ./dags:/root/airflow/dags
      - ./logs:/root/airflow/logs

volumes:
  postgres-db-volume:
