---
channels:
  - default

dependencies:
  - python=3.9
  - pandas >= 1.3
  - psycopg2
  - pip
  - pip:
    - 'apache-airflow[amazon,celery,dask,discord,docker,ftp,pandas,postgres,redis] >= 2.2'
    #- dagster
    - dagster_airflow
